### ISSUE TITLE
MQTT publish every second

### ISSUE THREAD

**Issue by jeng37** [lrswss/esp8266-wifi-power-meter#11]
Hello everyone,
First of all thanks for the great project.
only i have one problem,
mqtt publish is executed after each read.
I even entered the code (Hard-coded 90 sec) but it published every approx +- 1 seconds further.
Somehow the variable is not read?

**Comment by lrswss** [comment]
To help you, please provide us with more details on your setup:
- Have you successfully completed the calibration process?
- What were the min/max values during calibration? 
- Pulse threshold set under "Expert Settings"?
- Please post some consecutive MQTT messages

You don't need to modify the source code. All relevant parameters can be tuned under 'Expert settings'

**Comment by lrswss** [comment]
Closed due to missing feedback.
