### ISSUE TITLE
No ‚settings‘ in German UI

### ISSUE THREAD

**Issue by jeGit** [lrswss/esp8266-wifi-power-meter#12]
If you switch to German UI as mentioned in the description there is no ‘Settings’ Page loading after you click on the button.

**Comment by lrswss** [comment]
I tried to reproduce this error by flashing a new Wemos D1 mini, but the web UI works as expected, both in English and German. Do you see any errors on the serial console? Could you please uncomment DEBUG_HEAP in utils.h, recompile and post the serial output while trying to open the settings page.

**Comment by jeGit** [comment]
OK, It seems that the missing 'Settings' in German was a mistake as with a new flash it is there:
![Bildschirm­foto 2023-03-08 um 10 29 17](https://user-images.githubusercontent.com/23298068/223675513-d8febfba-cb54-4566-8eae-946328217176.jpg)

The UI flashing seems to go away once I went to the Settings menu, confirmed that 'MQTT' is disabled, saved and back to the main menu.
Only then the message (as in the video) 'Failed to publish to MQTT' disappears and with it the flash (constant reload of the page?) disappeared.
So maybe my sequence of working with it was a little bit off the usual path.
Thx for your quick replies.

**Comment by lrswss** [comment]
Did you install version 2.4.1? The flashing error message was actually caused by a missing check if MQTT is enabled/disabled in the main loop.

**Comment by jeGit** [comment]
Yes, updated now. All working as expected. Thanks.
