### ISSUE TITLE
Main page starts flashing

### ISSUE THREAD

**Issue by jeGit** [lrswss/esp8266-wifi-power-meter#13]
Main page starts flashing and displays MQTT error. 
MQTT is not activated in Settings. 
https://user-images.githubusercontent.com/23298068/222931889-25db709a-7dc5-4b8b-80d1-924101a82247.MOV

**Comment by lrswss** [comment]
To help you, I need a few more details about your setup: 1) First time installation or update (previous version)? 2) Browser used? 3) Compiled/Flashed with Arduino IDE (Version?) oder PlattformIO? Current settings as JSON?

I just did a fresh install with 2.4.0 on a new Wemos D1 recently (using PlatformIO) and did not run into problems like #12 or #13.

**Comment by jeGit** [comment]
Thanks for your reply. Was the video file accessible?
1. First time install
2. FF and Chrome on Mac and Edge on Windows
3. PlatformIO
No changes on the project files.
Please explain 'current settings as JSON'
