### ISSUE TITLE
MQTT Data not send

### ISSUE THREAD

**Issue by alkaraschu** [lrswss/esp8266-wifi-power-meter#14]
Hey Lars, great job and a very useful project. Thank you for your great idea! Initially all worked fine. The manual for installation is perfectly written. Now it happens, after restarts, that I do have a Wifi-connection (-65 dbm) but either the IR-sensor is not counting, data are not published over MQTT or both. The green lights of the module are working ( one permanently and one is flashing when the red mark is passing). Any Tips from your side?

**Comment by lrswss** [comment]
First time install or did you recently upgrade to the current version (2.4.1)? Do you see anything useful on the serial output of the Wemos D1 mini? Please post an excerpt from the serial output (including a system reset) here. Have you tried to set/calibrate a new threshold value for the red marker? Your MQTT settings: Auth on/off, TLS on/off?

**Comment by alkaraschu** [comment]
I did an upgrade to 2.4.1. MQTT publishing is running stabil now. Calibrating the threshold value for the red marker under high load is ending up with "Not enough measurements". Setting it to 75 or 50 doesn't bring the IR sensor to count the rounds even the one green light on the IR is flashing when the red marker is passing. I do not want to bother you. Thanks for help

**Comment by lrswss** [comment]
Did you eventually get it to work?

**Comment by alkaraschu** [comment]
yes, finally.  Started from scratch. New D1 and IR. New cables and upgrade to 2.4.1. Now it is running stable
