### ISSUE TITLE
MQTT: Check MQTT username/password

### ISSUE THREAD

**Issue by exergetiker** [lrswss/esp8266-wifi-power-meter#16]
When i want to save username and password for mqtt authentication, it rejects by displaying "Check MQTT username/password".

**Comment by lrswss** [comment]
Your language settings? Length of username/password?

**Comment by exergetiker** [comment]
Sorry for late answer. Got frustrated ;)
Language settings are default/english. Username is a letter and a number. So indeed quite short, but it works with ai-on-the-edge for example. Password has seven digits.

**Comment by lrswss** [comment]
Username and password must each have at least 3 characters

**Comment by exergetiker** [comment]
Alright, thanks for the hint. I changed the lenght check in the sourcecode, so it works now with my default mqtt broker.
