### ISSUE TITLE
error: call of overloaded 'abs(uint32_t)' is ambiguous

### ISSUE THREAD

**Issue by Conor-Burns** [lrswss/esp8266-wifi-power-meter#2]
Hi,
sehr cooles Projekt da es den Analogen output benutzt!
Leider erhalte ich beim kompilieren den Fehler im Titel für die Zeilen: 331, 793, 838 und 857

**Comment by lrswss** [comment]
Da ich inzwischen (für andere Projekte) auf PlatformIO umgestiegen bin, hatte ich meine Arduino IDE schon eine Weile nicht mehr aktualisiert. Mit der 1.8.10 gibt es (noch) keine Warnungen, mit der aktuellen 1.8.15 und aktuellen ESP8266 Tools hingegen schon. Ich habe den problematisch `abs(uint32_t)` Aufruf für den Zeitstempelvergleich mit millis() nun in ein eigene Funktion verpackt.

**Comment by Conor-Burns** [comment]
Ja ich benutze auch platformio für alles und hatte das importiert.

Dankeschön ich probier das nachher mal aus

**Comment by Conor-Burns** [comment]
@lrswss Das funktioniert soweit doch jetzt hab ich dieses problem:
```
  431 |     snprintf(clientid, sizeof(clientid), MQTT_CLIENT_ID, random(0xffff));
      |                                          ^~~~~~~~~~~~~~
Compiling .pio/build/d1_mini/FrameworkArduino/StreamSend.cpp.o
Compiling .pio/build/d1_mini/FrameworkArduino/Tone.cpp.o
Compiling .pio/build/d1_mini/FrameworkArduino/TypeConversion.cpp.o
/home/conor/Documents/PlatformIO/Projects/210808-200442-d1_mini/src/esp8266-wifi-power-meter.ino:469:1: error: control reaches end of non-void function [-Werror=return-type]
  469 | }
      | ^
```

**Comment by lrswss** [comment]
So, das Projekt lässt sich nun auch unter PlatformIO compilieren.

**Comment by Conor-Burns** [comment]
mega, dankeschön!
