### ISSUE TITLE
Publish totalConsumption and runtime?

### ISSUE THREAD

**Issue by steakneedy** [lrswss/esp8266-wifi-power-meter#8]
Hi there,

first of all thanks for the great work!

Would it be possible to also publish the total consumption via MQTT or am missing something?
I can get the data by HTTP Request, but it would be great to also have this data directly available as an entity in Home Assistant.

Thanks

**Comment by lrswss** [comment]
Hmmm...did you take a closer look at the settings tab? Simply enable MQTT, specify the IP address and port of your MQTT broker, set "Publish data as JSON" and check the option for "Home Assistant discovery" (see screenshots in README). The WiFi power meter will then show up in Home Assistant as a device with all its entities including total consumption and current runtime.

**Comment by steakneedy** [comment]
Yes, MQTT is enabled, data is published as json and I am also using the discovery feature. I do have the runtime, but total consumption is missing?

These 4 entities show up with the device:
- sensor.wifi_power_meter_74dae9_ferraris_impuls_counter
- sensor.wifi_power_meter_74dae9_current_power_consumption
- sensor.wifi_power_meter_74dae9_uptime
- sensor.wifi_power_meter_74dae9_wifi_signal_strength

**Comment by lrswss** [comment]
All 4 entities displayed in the web ui are published via MQTT along with RSSI and version number. Could you please check the messages published to your broker with MQTT Explorer oder mosquitto_sub on the topic you configured under "settings". Are you using the Arduino IDE or PlatformIO to compile the software? ArduinoJson Version? Operating system?

**Comment by steakneedy** [comment]
Thanks, you are right. The json published contains counter, consumption, power, runtime, rssi and version. 

![image](https://user-images.githubusercontent.com/99094183/199208382-0418e80c-2e65-45f7-81dc-8d74f78e6bc7.png)

Seems like there seems to be something messed up in Home Assistant because consumption isnt showing up?

![image](https://user-images.githubusercontent.com/99094183/199208145-64ec30e9-cb6f-4fbe-a5fe-59397210265a.png)

**Comment by lrswss** [comment]
Could you please check the topic HA discovery topic homeassistant/sensor/wifipowermeter-74DAE9 with MQTT Explorer. You should see 5 entities: pulse_count, total_consumption, current_power, signal_strength and runtime. It might help to remove the power meter's entry from HA's devices page and delete the above mentioned topic. Then restart the power meter to retrigger HA MQTT discovery.

**Comment by steakneedy** [comment]
I only have the 4 entities:

![image](https://user-images.githubusercontent.com/99094183/199418877-bacc5cd2-4971-4cb8-9f1b-0f50e8f99f18.png)

Restarted the power meter as well as Home Assistant.

**Comment by lrswss** [comment]
IDE? Operating system? ArduinoJSON version? Did you remove the topic homeassistant/sensor/wifipowermeter-74DAE9?

**Comment by steakneedy** [comment]
VSCode, Win10, ArduinoJson@6.19.4 and yes removed topic before reboot

**Comment by lrswss** [comment]
Just a wild guess: try to increase the size of StaticJsonDocument in mqtt.c (line 30) from 512 to 640.

**Comment by steakneedy** [comment]
Good idea, unfortunately didnt help. What else could it be?

If I stand correct, right now homeassistant/sensor/wifipowermeter-74DAE9/total_consumption is missing, therefore the entity isnt showing up in HA.

**Comment by lrswss** [comment]
I have no idea why this topic doesn't show up in your setup. Never had this problem. Could you please post the output from the PlatformIO console, when you compile the software. Everything from "PLATFORM:" up to and including the "Dependency Graph".

I'm on vacation right now, so I can't do any further testing with my wifi power meter. I will get back to you at the beginning of next week.

**Comment by xammmue** [comment]
Hello,
installed the meter yesterday and switched on home assistant discovery this morning.
I do as well only get 4 entities inside home assistant, total consumption is missing here too.
Those are the entities I do have:
```
homeassistant/sensor/wifipowermeter-7A0979/pulse_count
homeassistant/sensor/wifipowermeter-7A0979/current_power
homeassistant/sensor/wifipowermeter-7A0979/signal_strength
homeassistant/sensor/wifipowermeter-7A0979/runtime
```

Using firmware 223.
I compiled the firmware using Win10 and VSCode as well. I will later also check on the ArduinoJSON version. 

The jsonData published to the other mqtt topic which is not used for home assistant looks just fine:
`{"counter":907,"consumption":85492.88,"power":1495,"runtime":"0d0h10m","rssi":-44,"version":223}`

**Comment by lrswss** [comment]
I just checked my MQTT broker at home: the home assistant discovery message for "total_consumption" has 405 Bytes and should fit into the allocated char buffer and StaticJsonDocument according to the ArduinoJson Assistant. I'm using VS Code with PlatformIO on MacOS and discovery is working as expected. I'm pretty sure it's all about buffer allocation an different platforms: please try to increase StaticJsonDocument  in mqtt.c (line 30) from 512 to 640 and buf (line 32) from 448 to 512.

**Comment by xammmue** [comment]
Just rebuilt the firmware with the changes mentioned, but the behavior did not change. I did have to set up all the settings again as they somehow got lost. Even had to set up wifi which worked just out of the box after flashing the firmware via USB yesterday (probably because of the firmware installed previously).

I also looked up my ArduinoJson version now, which is 6.19.4. So same as steakneedy.

The other discovery messages have lengths of 338 to 404 bytes. I don't see why the total power one should be a huge difference here...

Is there a way to upload the config without having to set all the settings again? That would be great for testing purposes

**Comment by lrswss** [comment]
Does either of you have TLS enabled?

**Comment by lrswss** [comment]
> Is there a way to upload the config without having to set all the settings again? That would be great for testing purposes

Please use `config.h` for individual sensor presets.

**Comment by xammmue** [comment]
> Does either of you have TLS enabled?

I don't

**Comment by lrswss** [comment]
Increasing MQTT buffer size in mqtt.c at line 179 from 480 to 512 bytes seems to fix the problem. Can you confirm?

**Comment by xammmue** [comment]
I am pretty sure I tried that out 2 days ago and uploaded the new firmware via OTA onto my D1 mini, but it still did not send the message, double checked that with mqtt explorer.

Manually building and sending the message to the topic works, and the value also did get updated for a day, but that only worked until a restart of home assistant I believe

**Comment by lrswss** [comment]
It's definitely a MQTT buffer size issue. Actually it has to be increased to at least 672 bytes. Buffer size for the serialized JSON has to be set to 592 bytes and the StaticJsonDocument to 640 bytes accordingly. I'll release a new version with adjusted buffer sizes in `mqtt.c` shortly after few more tests.

Output of new function `publishJSON()` in `mqtt.c` which now explicitly checks for JSON overflow after serialization and the MQTT publish return value using a MQTT buffer of 672 bytes in `mqttInit()`:
```
Sending home asssistant MQTT auto-discovery message...
MQTT homeassistant/sensor/wifipowermeter-123456/pulse_count/config (341 bytes)
MQTT homeassistant/sensor/wifipowermeter-123456/total_consumption/config (424 bytes) <- OK
MQTT homeassistant/sensor/wifipowermeter-123456/current_power/config (406 bytes)
MQTT homeassistant/sensor/wifipowermeter-123456/signal_strength/config (352 bytes)
MQTT homeassistant/sensor/wifipowermeter-123456/runtime/config (340 bytes)
```

Same with current and way too small MQTT buffer size (480 bytes):
```
Sending home asssistant MQTT auto-discovery message...
MQTT homeassistant/sensor/wifipowermeter-123456/pulse_count/config (341 bytes)
MQTT homeassistant/sensor/wifipowermeter-123456/total_consumption/config failed! <- ERROR, not published
MQTT homeassistant/sensor/wifipowermeter-123456/current_power/config (406 bytes)
MQTT homeassistant/sensor/wifipowermeter-123456/signal_strength/config (352 bytes)
MQTT homeassistant/sensor/wifipowermeter-123456/runtime/config (340 bytes)
```
